docs_dir: "docs"
repo_url: "https://github.com/Krow10/pyfirehose"
site_dir: "site/docs/"
site_name: "PyFirehose docs"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github  
  name: material