name: Extract Firehose

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  firehose:
    runs-on: ubuntu-latest
    env:
      FIREHOSE_API_TOKEN: ${{ secrets.DFUSE_TOKEN }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.11"
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: sudo apt-get install jq
    - run: jq '.auth.eosnation.api_key = "'"$FIREHOSE_API_TOKEN"'" | .default = "eos_firehose_v1" | (.grpc[] | select(.id == "eos_firehose_v1") | .stub) |= "pyfirehose/config/dfuse/producerpay.hjson"' <<< "$(hjson -j pyfirehose/sample.config.hjson)" > pyfirehose/config.hjson
    - run: scripts/producerpay.sh
    - run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated data extraction for BP accounts
        commit_author: firehosebot <firehosebot@users.noreply.github.com>
        file_pattern: '*.jsonl'
