# Simple workflow for deploying static content to GitHub Pages
name: Deploy Website

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: [site/**]
  workflow_run:
    workflows: ["Update Index"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: actions/setup-python@v4
        with:
            python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r site/requirements.txt
      - name: Convert notebook to HTML
        run: |
          cd site/
          jupyter nbconvert --to html index.ipynb
          mv index.html static/
      - name: Upload Juypter artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/static'
      - name: Build docs to HTML
        run: python -m mkdocs build
      - name: Upload mkdocs artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Commit HTML static file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated static HTML page update for BP accounts
          file_pattern: '*.html'
