name: Update Index

on:
  push:
    branches: ["main"]
    paths: [jsonl/**]
    
  workflow_run:
    workflows: ["Extract Firehose"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "notebook"
  cancel-in-progress: true

jobs:
  notebook_update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r site/requirements.txt
      - name: Update analysis notebook
        run: jupyter nbconvert --to notebook --execute site/index.ipynb --ExecutePreprocessor.kernel_name='python3' --inplace
      - name: Commit updated notebook
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated index notebook update for BP accounts
          file_pattern: '*.ipynb'
